name: Metrics
on:
  schedule: [{cron: "0 14 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      # See action.yml for all options
      - name: lowlighter/metrics 😁
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: mikey-
          base: header, activity, community, repositories, metadata
          config_display: large
          config_order: introduction, base.header, base.activity+community, base.repositories, base.metadata, notable, followup, reactions, stackoverflow, people, languages, achievements, activity
          config_timezone: Australia/Melbourne
          plugin_achievements: yes
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: X
          plugin_activity: yes
          plugin_activity_days: 360
          plugin_activity_filter: push, issue, pr, review, comment, wiki, fork, public, member, release, ref/create, ref/delete
          plugin_activity_limit: 30
          plugin_activity_load: 35
          plugin_activity_timestamps: yes
          plugin_activity_visibility: all
          plugin_followup: yes
          plugin_followup_sections: all
          plugin_introduction: yes
          plugin_introduction_title: yes
          plugin_languages: yes
          plugin_languages_details: bytes-size, percentage
          plugin_languages_limit: 0
          plugin_languages_recent_days: 365
          plugin_languages_recent_load: 1000
          plugin_languages_ignored: Go, TypeScript, EJS, Obective-C, 
          plugin_languages_sections: most-used, recently-used
          plugin_languages_threshold: 0%
          plugin_notable: yes
          plugin_notable_repositories: yes
          plugin_people: yes
          plugin_people_types: owner, collaborator, organization_member
          plugin_reactions: yes
          plugin_stackoverflow: yes
          plugin_stackoverflow_user: 5188080
          repositories: 100
          repositories_affiliations: owner, collaborator, organization_member
          repositories_forks: yes

