name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 14 * * *"}]
  # Lines below let you run workflow manually and on each commit (optional)
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      # See action.yml for all options
      - name: lowlighter/metrics 😁
        uses: lowlighter/metrics@latest
        with:
          user: mikey-
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, activity, community, repositories, metadata
          repositories: 100
          repositories_forks: yes
          repositories_affiliations: owner, collaborator, organization_member
          plugin_skyline: yes
          plugin_skyline_year: 2021
          plugin_skyline_frames: 120
          plugin_skyline_quality: 1
          plugin_skyline_compatibility: yes
          plugin_languages: yes
          plugin_languages_limit: 0
          plugin_languages_colors: "javascript:#78c9f5, #955dd9:shell, ruby:#b00904, python:#075c1e"
          plugin_languages_sections: most-used, recently-used
          plugin_languages_details: bytes-size, percentage
          plugin_languages_recent_load: 1000
          plugin_languages_recent_days: 0
          plugin_achievements: yes
          plugin_achievements_secrets: yes
          plugin_achievements_limit: 1000
          plugin_reactions: yes
          plugin_activity: yes
          plugin_activity_load: 1000
          plugin_activity_days: 0
          plugin_activity_filter: all
          plugin_activity_visibility: all
